# sonar-project.properties
sonar.projectKey=LeeKHao_8.2CDevSecOps
sonar.organization=leekhao
sonar.host.url=https://sonarcloud.io
sonar.login=$44214e5987df039cf06d35c0eb53a001aae0ba08
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
